version: '3.4'

services:
  banking.operation.contact.api:
    image: ${DOCKER_REGISTRY-}bankingoperationcontactapi
    build:
      context: .
      dockerfile: Banking.Operation.Contact.Api/Dockerfile
      
networks:
  default:
    external: true
    name: bankingoperation-client-api_backend